name = "papabos/jam_template"
version = "0.1.0"
description = "jam template"
authors = ["papabos"]
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "jiwonz/pesde_scripts_rojo", version = "^0.1.0-rc.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
LemonSignal = { wally = "data-oriented-house/lemonsignal", version = "^1.10.0" }
Janitor = { wally = "howmanysmall/janitor", version = "^1.18.3" }
Moonlite = { wally = "maximumadhd/moonlite", version = "^0.9.0" }
Spring = { wally = "sleitnick/spring", version = "^1.0.0" }
Promise = { wally = "howmanysmall/typed-promise", version = "^4.0.6" }
